### ISSUE TITLE
[ 2021-08-22 07:08:17  youtube  ERROR ] ERROR: unable to download video data: HTTP Error 403: Forbidden [ 2021-08-22 07:08:17 BiliSession  ERROR ] 无法下载指定资源 - ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#10]
[ 2021-08-22 07:08:17  youtube  ERROR ] ERROR: unable to download video data: HTTP Error 403: Forbidden
[ 2021-08-22 07:08:17 BiliSession  ERROR ] 无法下载指定资源 - ERROR: unable to download video data: HTTP Error 403: Forbidden
[ 2021-08-22 07:08:17     root WARNING ] 上传未完毕
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
youtube限流问题，稍后再试？
