### ISSUE TITLE
新的报错。。。

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#11]
[ 2021-08-22 15:37:30 BiliSession WARNING ] < bvid : "" , title : "低糖低油綠豆糕 part2台灣1001個故事", desc : "请多多支持我" , video_endpoint : "" > 上传失败 : 请不要反复提交相同标题的稿件
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV13h411q7C8
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1xA411c75k
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1og41157Wn
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1Hh411q734
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1A64y1v77n
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1KL4y1v7r2
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1dL4y1a71x
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV1Z44y1k7qj
[ 2021-08-22 15:37:30 BiliSession   INFO ] 上传成功 - BVid: BV12f4y1P71N
[ 2021-08-22 15:37:30     root WARNING ] 上传未完毕
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
"完毕"条件是所有稿件都上传成功，否则exit code会是1
问题和日志应该一致，可以忽略
