### ISSUE TITLE
上传失败! - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) [ 2021-08-23 10:36:05     root WARNING ] 上传未完毕 Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#13]
[ 2021-08-23 10:36:05 BiliSession CRITICAL ] 上传失败! - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[ 2021-08-23 10:36:05     root WARNING ] 上传未完毕
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
上传太频繁了吧？
建议把列表分得小一些，~4个一份，分别部署
优势在出错代价小，而且速度会相对快一些
