### ISSUE TITLE
用户名和密码没有错误，但是却报错

### ISSUE THREAD

**Issue by genkimaru** [greats3an/bilibili-toolman#14]
![image](https://user-images.githubusercontent.com/5584476/131836359-48467084-8189-436c-997b-6399a4722e40.png)
bilibili_toolman.bilisession.common.LoginException: 登陆失败：'NoneType' object is not subscriptable
<Response 200>:{"code":-629,"message":"用户名或密码错误","ttl":1,"data":null}
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
用户名指的是在[B站个人中心](https://account.bilibili.com/account/setting)可见的用户名，你是输入了昵称吗？

其次用户名也可以用绑定的手机号代替，还请试试
