### ISSUE TITLE
b站账号无法登录

### ISSUE THREAD

**Issue by myishh** [greats3an/bilibili-toolman#16]
10月17号出现此问题，尝试更换多个账号后，确认账号没问题，始终提示

{'code': 86066, 'message': '该账号冻结中', 'ttl': 1, 'data': None}

**Comment by greats3an** [comment]
PC的上传助手换了新的`appkey`和`appsecret`，使用旧版本token进行**手机号和密码**登陆都会这样

而新的版本干掉了密码登陆？只留了短信验证的入口（不过不用二次验证

[最近](https://github.com/greats3an/bilibili-toolman/commit/f54fb5e95f6e9d6f22a7b5d1366e0b0d2366c5aa#diff-d4d8377584800e7a29d83c4badc716b5d6c15a846486d83fb50c05c6576301ec)把新token挖出来了，并且把短信登陆实现了下，可以看看现在的 [README](https://github.com/greats3an/bilibili-toolman/blob/master/README.md)
