### ISSUE TITLE
报错了！

### ISSUE THREAD

**Issue by googidaddy** [greats3an/bilibili-toolman#2]
你好，在虚拟环境中按你给的格式我执行了程序，但是报错了，错误显示我提供了4个参数，但是程序只需要3个

**Comment by greats3an** [comment]
能给个错误输出吗？

**Comment by googidaddy** [comment]
![image](https://user-images.githubusercontent.com/63139246/107137335-98f8c700-6946-11eb-9fc8-aef107c2b362.png)

**Comment by greats3an** [comment]
[小改了下](https://github.com/greats3an/bilibili-toolman/commit/1d95c2c07f87d000a7cf546f96f5b0791dd10be8)
你的cookie应该是这样的：
`SESSDATA=f281c417%2CXXXXXXXX%2Cca785%2A21;bili_jct=383d249XXXXXXXXX8740244fe4e916`

**Comment by googidaddy** [comment]
嗯我重新试了试，现在是invalid cookies：账号未登录

**Comment by greats3an** [comment]
方便贴下 cookie 吗

**Comment by googidaddy** [comment]
python bilibili-toolman.py --cookies "cookies=SESSDATA=2c7b4d00xxxxxx2A21;bili_jct=80dxxxx39ca" --youtube "https://www.youtube.com/watch?v=_3Mo7U0XSFo" --thread_id 17 --tags "majima,goro,majima goro" --opts "format=best"

**Comment by greats3an** [comment]
淦 [打错了](https://github.com/greats3an/bilibili-toolman/commit/50bf084be8d0fe4c83f184d79e02af03597f7ef9)

`	python bilibili-toolman.py --cookies "SESSDATA=cb0..; bili_jct=6750..." --youtube "https://www.youtube.com/watch?v=_3Mo7U0XSFo" --thread_id 17 --tags "majima,goro,majima goro" --opts "format=best"    `

应该没有 `cookies=`

**Comment by googidaddy** [comment]
> 淦 [打错了](https://github.com/greats3an/bilibili-toolman/commit/50bf084be8d0fe4c83f184d79e02af03597f7ef9)
> 
> ` python bilibili-toolman.py --cookies "SESSDATA=cb0..; bili_jct=6750..." --youtube "https://www.youtube.com/watch?v=_3Mo7U0XSFo" --thread_id 17 --tags "majima,goro,majima goro" --opts "format=best" `
> 
> 应该没有 `cookies=`

😓！小事小事

**Comment by googidaddy** [comment]
![image](https://user-images.githubusercontent.com/63139246/107152507-4dc0d180-69a3-11eb-840e-16ab82630c0c.png)
卡在fetching token是正常的吗？

**Comment by greats3an** [comment]
没装 `tqdm` 呢

这样没上传好；补上tqdm后再试试？

**Comment by googidaddy** [comment]
> 没装 `tqdm` 呢
> 
> 这样没上传好；补上tqdm后再试试？

好 我试试

**Comment by googidaddy** [comment]
> 没装 `tqdm` 呢
> 
> 这样没上传好；补上tqdm后再试试？
好像很容易卡在了Fetching token那里，具体是不是那边endpoint网络拥堵的问题？
![image](https://user-images.githubusercontent.com/63139246/107152734-785f5a00-69a4-11eb-980e-3010d4b6e535.png)

**Comment by googidaddy** [comment]
发现是那边server把我拒绝了，应该可以加proxy啥的，明天我帮你完善一下readme吧，谢谢大佬 早点睡吧

**Comment by greats3an** [comment]
好的，多谢了
