### ISSUE TITLE
question

### ISSUE THREAD

**Issue by googidaddy** [greats3an/bilibili-toolman#3]
问一下哦，你用哪的服务器的，我这里上传线路好慢。。
![image](https://user-images.githubusercontent.com/63139246/107390732-f0f42100-6b32-11eb-8328-2dcfb9518002.png)

**Comment by greats3an** [comment]
> 问一下哦，你用哪的服务器的，我这里上传线路好慢。。
> ![image](https://user-images.githubusercontent.com/63139246/107390732-f0f42100-6b32-11eb-8328-2dcfb9518002.png)

![image](https://user-images.githubusercontent.com/31397301/109390988-b1f60600-794f-11eb-85af-ee90cae33149.png)
我用电信家宽的，可以满速

**Comment by googidaddy** [comment]
> > 问一下哦，你用哪的服务器的，我这里上传线路好慢。。
> > ![image](https://user-images.githubusercontent.com/63139246/107390732-f0f42100-6b32-11eb-8328-2dcfb9518002.png)
> 
> ![image](https://user-images.githubusercontent.com/31397301/109390988-b1f60600-794f-11eb-85af-ee90cae33149.png)
> 我用电信家宽的，可以满速

我换了一下，不用百度的。也可以满速。
