### ISSUE TITLE
下载视频证书问题

### ISSUE THREAD

**Issue by ahxinin** [greats3an/bilibili-toolman#4]
错误日志：
[ 2021-06-06 13:36:21  youtube  DEBUG ] [youtube] fypO-lbSNno: Downloading API JSON
[ 2021-06-06 13:36:21  youtube  ERROR ] ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
[ 2021-06-06 13:36:21 BiliSession  ERROR ] Cannot download specified resource - ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
[ 2021-06-06 13:36:21     root WARNING ] Dirty flag set,not all tasks are done properly

请教一下，如何解决

**Comment by greats3an** [comment]
可以试试加参数 `--opts "no_check_certificate=True"` 跳过 SSL 检测

`--youtube "https://www.youtube.com/watch?v=fypO-lbSNno" --opts "no_check_certificate=True"`

**Comment by ahxinin** [comment]
下载最新代码，使用以下命令，还是相同的错误

bilibili-toolman.py --cookies "" --youtube "https://www.youtube.com/watch?v=fypO-lbSNno" --opts "no_check_certificate=True"

**Comment by greats3an** [comment]
确认下安装了`certifi`([urllib and “SSL: CERTIFICATE_VERIFY_FAILED” Error](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357))
或者删掉`https`?:`bilibili-toolman.py --cookies "" --youtube "http://www.youtube.com/watch?v=fypO-lbSNno" --opts "no_check_certificate=True"`

**Comment by Awelling2** [comment]
same question for me,如果你是mac os 可以尝试这个https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
