### ISSUE TITLE
大佬，有没有更简单的编译版本，便于直接运行

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#5]
教程的这些一步步操作比较复杂，对系统环境要求也比较高，主要是使用时不太方便逐条输命令。。。

**Comment by greats3an** [comment]
可供参考：[使用 Github Actions 转载视频](https://github.com/greats3an/bilibili-toolman/tree/1.0.4.4#%E4%BD%BF%E7%94%A8-github-actions-%E8%BD%AC%E8%BD%BD%E8%A7%86%E9%A2%91)
