### ISSUE TITLE
另外，大佬，这个脚本可以批量上传视频么？

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#7]

**Comment by greats3an** [comment]
可以在youtube创建播放列表，然后把列表作视频链接填入
转载设置加 `--seperate_parts` 可以让每个视频各成一稿，否则会作为多P视频上传

**Comment by zhezhe168** [comment]
好的，另外转载时能不能不选择转载类别，选择自制，视频简介留白，这些可以设置么？

**Comment by zhezhe168** [comment]
有个新报错
Error: Process completed with exit code 127.

**Comment by zhezhe168** [comment]
[ 2021-08-22 03:40:22 BiliSession   INFO ]   - URI : https://www.youtube.com/watch?v=bziTRlyc-Jw
[ 2021-08-22 03:40:22  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading webpage
[ 2021-08-22 03:40:22  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading MPD manifest
[ 2021-08-22 03:40:23  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading thumbnail ...
[ 2021-08-22 03:40:23  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Writing thumbnail to: bziTRlyc-Jw.jpg
[ 2021-08-22 03:40:23  youtube  DEBUG ] [download] Destination: bziTRlyc-Jw.f137.mp4
[ 2021-08-22 03:40:23  youtube  DEBUG ] 
[download]   0.1% of 1.69MiB at 59.25KiB/s ETA 00:29
[ 2021-08-22 03:40:23  youtube  DEBUG ] 
[download]   0.2% of 1.69MiB at 168.41KiB/s ETA 00:10
[ 2021-08-22 03:40:23  youtube  DEBUG ] 
[download]   0.4% of 1.69MiB at 382.84KiB/s ETA 00:04
[ 2021-08-22 03:40:23  youtube  DEBUG ] 
[download]   0.9% of 1.69MiB at 789.20KiB/s ETA 00:02
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]   1.8% of 1.69MiB at 295.19KiB/s ETA 00:05
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]   3.6% of 1.69MiB at 358.52KiB/s ETA 00:04
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]   7.3% of 1.69MiB at 485.42KiB/s ETA 00:03
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]  14.7% of 1.69MiB at 746.80KiB/s ETA 00:01
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]  29.5% of 1.69MiB at  1.17MiB/s ETA 00:01
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download]  59.1% of 1.69MiB at  1.94MiB/s ETA 00:00
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download] 100.0% of 1.69MiB at  2.93MiB/s ETA 00:00
[ 2021-08-22 03:40:24  youtube  DEBUG ] 
[download] 100% of 1.69MiB in 00:01
[ 2021-08-22 03:40:25  youtube  DEBUG ] [download] Destination: bziTRlyc-Jw.f140.m4a
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   0.1% of 1.65MiB at 55.92KiB/s ETA 00:30
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   0.2% of 1.65MiB at 165.91KiB/s ETA 00:10
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   0.4% of 1.65MiB at 383.85KiB/s ETA 00:04
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   0.9% of 1.65MiB at 814.77KiB/s ETA 00:02
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   1.8% of 1.65MiB at 292.20KiB/s ETA 00:05
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   3.7% of 1.65MiB at 352.27KiB/s ETA 00:04
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]   7.5% of 1.65MiB at 472.57KiB/s ETA 00:03
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]  15.1% of 1.65MiB at 719.67KiB/s ETA 00:01
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]  30.2% of 1.65MiB at  1.14MiB/s ETA 00:01
[ 2021-08-22 03:40:25  youtube  DEBUG ] 
[download]  60.4% of 1.65MiB at  1.90MiB/s ETA 00:00
Error: Process completed with exit code 127.

**Comment by greats3an** [comment]
action的问题，重新运行？

**Comment by greats3an** [comment]
> 好的，另外转载时能不能不选择转载类别，选择自制，视频简介留白，这些可以设置么？

1.0.5 加了这个选项 ：`--original            设置稿件为原创`
留白简介可填 `--desc -`，毕竟B站不允许空简介🤔

**Comment by zhezhe168** [comment]
action重新运行依旧报错Error: Process completed with exit code 127.

**Comment by greats3an** [comment]
我这里没法重现这个问题
'''
[ 2021-08-22 06:02:20 BiliSession   INFO ]   - URI : https://www.youtube.com/watch?v=bziTRlyc-Jw
[ 2021-08-22 06:02:21  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading webpage
[ 2021-08-22 06:02:21  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading MPD manifest
[ 2021-08-22 06:02:21  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Downloading thumbnail ...
[ 2021-08-22 06:02:21  youtube  DEBUG ] [youtube] bziTRlyc-Jw: Writing thumbnail to: bziTRlyc-Jw.jpg
[ 2021-08-22 06:02:22  youtube  DEBUG ] [download] Destination: bziTRlyc-Jw.f137.mp4
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   0.1% of 1.69MiB at 42.71KiB/s ETA 00:40
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   0.2% of 1.69MiB at 127.07KiB/s ETA 00:13
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   0.4% of 1.69MiB at 293.91KiB/s ETA 00:05
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   0.9% of 1.69MiB at 625.32KiB/s ETA 00:02
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   1.8% of 1.69MiB at 216.92KiB/s ETA 00:07
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   3.6% of 1.69MiB at 264.31KiB/s ETA 00:06
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]   7.3% of 1.69MiB at 357.34KiB/s ETA 00:04
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]  14.7% of 1.69MiB at 546.08KiB/s ETA 00:02
[ 2021-08-22 06:02:22  youtube  DEBUG ] 
[download]  29.5% of 1.69MiB at 880.60KiB/s ETA 00:01
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]  59.1% of 1.69MiB at  1.22MiB/s ETA 00:00
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download] 100.0% of 1.69MiB at  2.03MiB/s ETA 00:00
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download] 100% of 1.69MiB in 00:01
[ 2021-08-22 06:02:23  youtube  DEBUG ] [download] Destination: bziTRlyc-Jw.f140.m4a
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   0.1% of 1.65MiB at 53.80KiB/s ETA 00:31
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   0.2% of 1.65MiB at 160.13KiB/s ETA 00:10
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   0.4% of 1.65MiB at 370.29KiB/s ETA 00:04
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   0.9% of 1.65MiB at 785.16KiB/s ETA 00:02
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   1.8% of 1.65MiB at 233.79KiB/s ETA 00:07
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   3.7% of 1.65MiB at 282.43KiB/s ETA 00:05
[ 2021-08-22 06:02:23  youtube  DEBUG ] 
[download]   7.5% of 1.65MiB at 375.94KiB/s ETA 00:04
[ 2021-08-22 06:02:24  youtube  DEBUG ] 
[download]  15.1% of 1.65MiB at 574.09KiB/s ETA 00:02
[ 2021-08-22 06:02:24  youtube  DEBUG ] 
[download]  30.2% of 1.65MiB at 927.63KiB/s ETA 00:01
[ 2021-08-22 06:02:24  youtube  DEBUG ] 
[download]  60.4% of 1.65MiB at  1.51MiB/s ETA 00:00
[ 2021-08-22 06:02:24  youtube  DEBUG ] 
[download] 100.0% of 1.65MiB at  2.24MiB/s ETA 00:00
[ 2021-08-22 06:02:24  youtube  DEBUG ] 
[download] 100% of 1.65MiB in 00:01
[ 2021-08-22 06:02:24  youtube  DEBUG ] [ffmpeg] Merging formats into "bziTRlyc-Jw.mp4"
[ 2021-08-22 06:02:24  youtube  DEBUG ] Deleting original file bziTRlyc-Jw.f137.mp4 (pass -k to keep)
[ 2021-08-22 06:02:24  youtube  DEBUG ] Deleting original file bziTRlyc-Jw.f140.m4a (pass -k to keep)
[ 2021-08-22 06:02:24     root   INFO ] 上传资源数：1
[ 2021-08-22 06:02:24 BiliSession   INFO ] 准备上传: July - Love Theme
[ 2021-08-22 06:02:24 BiliSession  DEBUG ] 上传分块: 2
[ 2021-08-22 06:02:24 BiliSession  DEBUG ] 分块大小: 2097152 B
↑: 0.00B [00:00, ?B/s]
↑:   0%|          | 0.00/3.55M [00:00<?, ?B/s]
↑: 100%|██████████| 3.55M/3.55M [00:43<00:00, 7.09MB/s]
[ 2021-08-22 06:03:08 BiliSession  DEBUG ] MD5: 80e81b9033f107dc6515a3c8edad1d63
[ 2021-08-22 06:03:08 BiliSession  DEBUG ] 上传完毕: (OK/1 info/Successful.)
[ 2021-08-22 06:03:08 BiliSession  DEBUG ] bziTRlyc-Jw.jpg -> image/jpeg
[ 2021-08-22 06:03:08 BiliSession  DEBUG ] 上传封面图 (46354 B)
[ 2021-08-22 06:03:09 BiliSession   INFO ] 资源已上传
[ 2021-08-22 06:03:09 BiliSession  DEBUG ] bziTRlyc-Jw.jpg -> image/jpeg
[ 2021-08-22 06:03:09 BiliSession  DEBUG ] 上传封面图 (46354 B)
[ 2021-08-22 06:03:09 BiliSession  DEBUG ] 准备提交多 P 内容: July - Love Theme
'''
sync with upstream后重建workflow应该可以解决

**Comment by zhezhe168** [comment]
大佬可以把需要填的转载设置的这个example参数发我看下么，我对照看看是不是参数什么的有问题

**Comment by greats3an** [comment]
视频链接: https://www.youtube.com/watch?v=bziTRlyc-Jw
转载设置: --tags 测试 --thread_id 28

不过看日志好像没到上传的部分，问题和设置应该关系不大🤔

**Comment by zhezhe168** [comment]
是这个格式么
--seperate_parts --tags 烹饪,美食 --thread_id 76

**Comment by greats3an** [comment]
> 是这个格式么
> --seperate_parts --tags 烹饪,美食 --thread_id 76

👌

**Comment by zhezhe168** [comment]
话说好像B站是可以空简介的，我手动上传时简介留空没问题

**Comment by zhezhe168** [comment]
大佬，自制声明的参数是哪个

**Comment by zhezhe168** [comment]
未经作者授权 禁止转载

**Comment by greats3an** [comment]
> 未经作者授权 禁止转载

[刚刚加入1.0.5.3](https://github.com/greats3an/bilibili-toolman/commit/d329b94a98c8829adaeb28d473cfe8d7fab71ac4),`--no_reprint          设置稿件不允许转载`
记得fork要更新😂

**Comment by zhezhe168** [comment]
谢谢大佬，我试试去

**Comment by greats3an** [comment]
这个参数要和--original一起使用，否则稿件会被视为转载
