### ISSUE TITLE
[ 2021-08-22 07:03:12 BiliSession  DEBUG ] 准备提交单 P 内容: July - Walking To Heaven [ 2021-08-22 07:03:12 BiliSession CRITICAL ] 其他错误 (21052): 稿件描述长度太长，已超过限制 - 跳过上传 [ 2021-08-22 07:03:12 BiliSession WARNING ] 上传失败: 稿件描述长度太长，已超过限制

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#9]
[ 2021-08-22 07:03:12 BiliSession  DEBUG ] 准备提交单 P 内容: July - Walking To Heaven
[ 2021-08-22 07:03:12 BiliSession CRITICAL ] 其他错误 (21052): 稿件描述长度太长，已超过限制 - 跳过上传
[ 2021-08-22 07:03:12 BiliSession WARNING ] 上传失败: 稿件描述长度太长，已超过限制

**Comment by greats3an** [comment]
没法重现，能把参数发上来吗？
```
[ 2021-08-22 15:23:49 BiliSession  DEBUG ] ztyROYIxH0Q.jpg -> image/jpeg
[ 2021-08-22 15:23:49 BiliSession  DEBUG ] 上传封面图 (46357 B)
[ 2021-08-22 15:23:49 BiliSession  DEBUG ] 准备提交单 P 内容: [July Official] July - Walking To Heaven
[ 2021-08-22 15:23:49 BiliSession   INFO ] 上传成功 - BVid: ********
```

**Comment by zhezhe168** [comment]
现在变成这个错误了：
Error: Process completed with exit code 127.
https://www.youtube.com/watch?v=bziTRlyc-Jw&list=PLBqEgyw01wJb4FE1W6aUL5KU3DTYXA5Fq
--seperate_parts --desc - --tags July,纯音乐 --thread_id 28

**Comment by zhezhe168** [comment]
不好意思地址错了，是这个地址：

https://www.youtube.com/playlist?list=PLBqEgyw01wJb4FE1W6aUL5KU3DTYXA5Fq
--seperate_parts --desc - --tags July,纯音乐 --thread_id 28

**Comment by greats3an** [comment]
action的127和找不到文件有关，把自己的Fork更新下试试？版本号应该是1.0.5.2了

现在标题、描述长度限制应该不是问题了；可以更新后拿 https://www.youtube.com/watch?v=Fxfa_oXGi2Q 试试

**Comment by zhezhe168** [comment]
我版本是最新的，有点奇怪。。。

**Comment by greats3an** [comment]
是你的repo没和我的对齐
[Syncing a fork from the web UI](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-from-the-web-ui)
更新之后但愿action不应该再出问题了😅

**Comment by zhezhe168** [comment]
这个更新方法没看到，小白github玩的不转，大佬有具体的截图教程嘛？

**Comment by greats3an** [comment]
![image](https://user-images.githubusercontent.com/31397301/130358495-db2934bf-6e7d-4982-8248-44ef4ff90857.png)
自己截了个，有点草

**Comment by zhezhe168** [comment]
谢谢
